FROM node:20-bookworm-slim AS build

ARG REACT_APP_VERSION
ARG REACT_APP_BASE_URL
ARG REACT_APP_API_URL
ARG GENERATE_SOURCEMAP

ENV REACT_APP_VERSION=${REACT_APP_VERSION} \
    REACT_APP_BASE_URL=${REACT_APP_BASE_URL} \
    REACT_APP_API_URL=${REACT_APP_API_URL} \
    GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP} 
ENV NODE_OPTIONS="--max-old-space-size=4096"

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    make \
    python3 \
    libexpat1-dev \
    && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

# nginx
FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
