services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile

    image: btlms-backend:${BTLMS_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - ./backend/.env

    ports:
      - "3501:3500"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        REACT_APP_VERSION: ${REACT_APP_VERSION:-v2.1.0}
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL:-/}
        REACT_APP_API_URL: ${REACT_APP_API_URL:-/}
        GENERATE_SOURCEMAP: ${GENERATE_SOURCEMAP:-false}

    image: btlms-frontend:${BTLMS_IMAGE_TAG:-latest}
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3002:80"
